// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wordDescriptor.proto

package personal.eido.ezmemory.data;

public final class WordProtos {
  private WordProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface WordOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string keyWord = 1;
    /**
     * <code>optional string keyWord = 1;</code>
     */
    boolean hasKeyWord();
    /**
     * <code>optional string keyWord = 1;</code>
     */
    java.lang.String getKeyWord();
    /**
     * <code>optional string keyWord = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyWordBytes();

    // optional string shortDescription = 2;
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    boolean hasShortDescription();
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    java.lang.String getShortDescription();
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    com.google.protobuf.ByteString
        getShortDescriptionBytes();

    // optional string longDescription = 3;
    /**
     * <code>optional string longDescription = 3;</code>
     */
    boolean hasLongDescription();
    /**
     * <code>optional string longDescription = 3;</code>
     */
    java.lang.String getLongDescription();
    /**
     * <code>optional string longDescription = 3;</code>
     */
    com.google.protobuf.ByteString
        getLongDescriptionBytes();

    // optional int32 rank = 4 [default = 5];
    /**
     * <code>optional int32 rank = 4 [default = 5];</code>
     */
    boolean hasRank();
    /**
     * <code>optional int32 rank = 4 [default = 5];</code>
     */
    int getRank();
  }
  /**
   * Protobuf type {@code data.Word}
   */
  public static final class Word extends
      com.google.protobuf.GeneratedMessageLite
      implements WordOrBuilder {
    // Use Word.newBuilder() to construct.
    private Word(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Word(boolean noInit) {}

    private static final Word defaultInstance;
    public static Word getDefaultInstance() {
      return defaultInstance;
    }

    public Word getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Word(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              keyWord_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              shortDescription_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              longDescription_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rank_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Word> PARSER =
        new com.google.protobuf.AbstractParser<Word>() {
      public Word parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Word(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Word> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string keyWord = 1;
    public static final int KEYWORD_FIELD_NUMBER = 1;
    private java.lang.Object keyWord_;
    /**
     * <code>optional string keyWord = 1;</code>
     */
    public boolean hasKeyWord() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string keyWord = 1;</code>
     */
    public java.lang.String getKeyWord() {
      java.lang.Object ref = keyWord_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          keyWord_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string keyWord = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyWordBytes() {
      java.lang.Object ref = keyWord_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string shortDescription = 2;
    public static final int SHORTDESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object shortDescription_;
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    public boolean hasShortDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    public java.lang.String getShortDescription() {
      java.lang.Object ref = shortDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          shortDescription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string shortDescription = 2;</code>
     */
    public com.google.protobuf.ByteString
        getShortDescriptionBytes() {
      java.lang.Object ref = shortDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string longDescription = 3;
    public static final int LONGDESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object longDescription_;
    /**
     * <code>optional string longDescription = 3;</code>
     */
    public boolean hasLongDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string longDescription = 3;</code>
     */
    public java.lang.String getLongDescription() {
      java.lang.Object ref = longDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          longDescription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string longDescription = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLongDescriptionBytes() {
      java.lang.Object ref = longDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 rank = 4 [default = 2];
    public static final int RANK_FIELD_NUMBER = 4;
    private int rank_;
    /**
     * <code>optional int32 rank = 4 [default = 2];</code>
     */
    public boolean hasRank() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 rank = 4 [default = 2];</code>
     */
    public int getRank() {
      return rank_;
    }

    private void initFields() {
      keyWord_ = "";
      shortDescription_ = "";
      longDescription_ = "";
      rank_ = 2;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyWordBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getShortDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLongDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rank_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyWordBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getShortDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLongDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rank_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.Word parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(personal.eido.ezmemory.data.WordProtos.Word prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code data.Word}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          personal.eido.ezmemory.data.WordProtos.Word, Builder>
        implements personal.eido.ezmemory.data.WordProtos.WordOrBuilder {
      // Construct using personal.eido.ezmemory.data.WordProtos.Word.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keyWord_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        shortDescription_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        longDescription_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        rank_ = 5;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public personal.eido.ezmemory.data.WordProtos.Word getDefaultInstanceForType() {
        return personal.eido.ezmemory.data.WordProtos.Word.getDefaultInstance();
      }

      public personal.eido.ezmemory.data.WordProtos.Word build() {
        personal.eido.ezmemory.data.WordProtos.Word result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public personal.eido.ezmemory.data.WordProtos.Word buildPartial() {
        personal.eido.ezmemory.data.WordProtos.Word result = new personal.eido.ezmemory.data.WordProtos.Word(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyWord_ = keyWord_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.shortDescription_ = shortDescription_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.longDescription_ = longDescription_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rank_ = rank_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(personal.eido.ezmemory.data.WordProtos.Word other) {
        if (other == personal.eido.ezmemory.data.WordProtos.Word.getDefaultInstance()) return this;
        if (other.hasKeyWord()) {
          bitField0_ |= 0x00000001;
          keyWord_ = other.keyWord_;
          
        }
        if (other.hasShortDescription()) {
          bitField0_ |= 0x00000002;
          shortDescription_ = other.shortDescription_;
          
        }
        if (other.hasLongDescription()) {
          bitField0_ |= 0x00000004;
          longDescription_ = other.longDescription_;
          
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        personal.eido.ezmemory.data.WordProtos.Word parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (personal.eido.ezmemory.data.WordProtos.Word) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string keyWord = 1;
      private java.lang.Object keyWord_ = "";
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public boolean hasKeyWord() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public java.lang.String getKeyWord() {
        java.lang.Object ref = keyWord_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          keyWord_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyWordBytes() {
        java.lang.Object ref = keyWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public Builder setKeyWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        keyWord_ = value;
        
        return this;
      }
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public Builder clearKeyWord() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyWord_ = getDefaultInstance().getKeyWord();
        
        return this;
      }
      /**
       * <code>optional string keyWord = 1;</code>
       */
      public Builder setKeyWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        keyWord_ = value;
        
        return this;
      }

      // optional string shortDescription = 2;
      private java.lang.Object shortDescription_ = "";
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public boolean hasShortDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public java.lang.String getShortDescription() {
        java.lang.Object ref = shortDescription_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          shortDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public com.google.protobuf.ByteString
          getShortDescriptionBytes() {
        java.lang.Object ref = shortDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public Builder setShortDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        shortDescription_ = value;
        
        return this;
      }
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public Builder clearShortDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        shortDescription_ = getDefaultInstance().getShortDescription();
        
        return this;
      }
      /**
       * <code>optional string shortDescription = 2;</code>
       */
      public Builder setShortDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        shortDescription_ = value;
        
        return this;
      }

      // optional string longDescription = 3;
      private java.lang.Object longDescription_ = "";
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public boolean hasLongDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public java.lang.String getLongDescription() {
        java.lang.Object ref = longDescription_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          longDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLongDescriptionBytes() {
        java.lang.Object ref = longDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public Builder setLongDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        longDescription_ = value;
        
        return this;
      }
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public Builder clearLongDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longDescription_ = getDefaultInstance().getLongDescription();
        
        return this;
      }
      /**
       * <code>optional string longDescription = 3;</code>
       */
      public Builder setLongDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        longDescription_ = value;
        
        return this;
      }

      // optional int32 rank = 4 [default = 5];
      private int rank_ = 5;
      /**
       * <code>optional int32 rank = 4 [default = 5];</code>
       */
      public boolean hasRank() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 rank = 4 [default = 5];</code>
       */
      public int getRank() {
        return rank_;
      }
      /**
       * <code>optional int32 rank = 4 [default = 5];</code>
       */
      public Builder setRank(int value) {
        bitField0_ |= 0x00000008;
        rank_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 rank = 4 [default = 5];</code>
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rank_ = 5;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:data.Word)
    }

    static {
      defaultInstance = new Word(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data.Word)
  }

  public interface WordListOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .data.Word word = 1;
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    java.util.List<personal.eido.ezmemory.data.WordProtos.Word> 
        getWordList();
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    personal.eido.ezmemory.data.WordProtos.Word getWord(int index);
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    int getWordCount();
  }
  /**
   * Protobuf type {@code data.WordList}
   */
  public static final class WordList extends
      com.google.protobuf.GeneratedMessageLite
      implements WordListOrBuilder {
    // Use WordList.newBuilder() to construct.
    private WordList(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private WordList(boolean noInit) {}

    private static final WordList defaultInstance;
    public static WordList getDefaultInstance() {
      return defaultInstance;
    }

    public WordList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private WordList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                word_ = new java.util.ArrayList<personal.eido.ezmemory.data.WordProtos.Word>();
                mutable_bitField0_ |= 0x00000001;
              }
              word_.add(input.readMessage(personal.eido.ezmemory.data.WordProtos.Word.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          word_ = java.util.Collections.unmodifiableList(word_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<WordList> PARSER =
        new com.google.protobuf.AbstractParser<WordList>() {
      public WordList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WordList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WordList> getParserForType() {
      return PARSER;
    }

    // repeated .data.Word word = 1;
    public static final int WORD_FIELD_NUMBER = 1;
    private java.util.List<personal.eido.ezmemory.data.WordProtos.Word> word_;
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    public java.util.List<personal.eido.ezmemory.data.WordProtos.Word> getWordList() {
      return word_;
    }
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    public java.util.List<? extends personal.eido.ezmemory.data.WordProtos.WordOrBuilder> 
        getWordOrBuilderList() {
      return word_;
    }
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    public int getWordCount() {
      return word_.size();
    }
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    public personal.eido.ezmemory.data.WordProtos.Word getWord(int index) {
      return word_.get(index);
    }
    /**
     * <code>repeated .data.Word word = 1;</code>
     */
    public personal.eido.ezmemory.data.WordProtos.WordOrBuilder getWordOrBuilder(
        int index) {
      return word_.get(index);
    }

    private void initFields() {
      word_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < word_.size(); i++) {
        output.writeMessage(1, word_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < word_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, word_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static personal.eido.ezmemory.data.WordProtos.WordList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(personal.eido.ezmemory.data.WordProtos.WordList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code data.WordList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          personal.eido.ezmemory.data.WordProtos.WordList, Builder>
        implements personal.eido.ezmemory.data.WordProtos.WordListOrBuilder {
      // Construct using personal.eido.ezmemory.data.WordProtos.WordList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        word_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public personal.eido.ezmemory.data.WordProtos.WordList getDefaultInstanceForType() {
        return personal.eido.ezmemory.data.WordProtos.WordList.getDefaultInstance();
      }

      public personal.eido.ezmemory.data.WordProtos.WordList build() {
        personal.eido.ezmemory.data.WordProtos.WordList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public personal.eido.ezmemory.data.WordProtos.WordList buildPartial() {
        personal.eido.ezmemory.data.WordProtos.WordList result = new personal.eido.ezmemory.data.WordProtos.WordList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          word_ = java.util.Collections.unmodifiableList(word_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.word_ = word_;
        return result;
      }

      public Builder mergeFrom(personal.eido.ezmemory.data.WordProtos.WordList other) {
        if (other == personal.eido.ezmemory.data.WordProtos.WordList.getDefaultInstance()) return this;
        if (!other.word_.isEmpty()) {
          if (word_.isEmpty()) {
            word_ = other.word_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWordIsMutable();
            word_.addAll(other.word_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        personal.eido.ezmemory.data.WordProtos.WordList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (personal.eido.ezmemory.data.WordProtos.WordList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .data.Word word = 1;
      private java.util.List<personal.eido.ezmemory.data.WordProtos.Word> word_ =
        java.util.Collections.emptyList();
      private void ensureWordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          word_ = new java.util.ArrayList<personal.eido.ezmemory.data.WordProtos.Word>(word_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public java.util.List<personal.eido.ezmemory.data.WordProtos.Word> getWordList() {
        return java.util.Collections.unmodifiableList(word_);
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public int getWordCount() {
        return word_.size();
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public personal.eido.ezmemory.data.WordProtos.Word getWord(int index) {
        return word_.get(index);
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder setWord(
          int index, personal.eido.ezmemory.data.WordProtos.Word value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWordIsMutable();
        word_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder setWord(
          int index, personal.eido.ezmemory.data.WordProtos.Word.Builder builderForValue) {
        ensureWordIsMutable();
        word_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder addWord(personal.eido.ezmemory.data.WordProtos.Word value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWordIsMutable();
        word_.add(value);

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder addWord(
          int index, personal.eido.ezmemory.data.WordProtos.Word value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWordIsMutable();
        word_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder addWord(
          personal.eido.ezmemory.data.WordProtos.Word.Builder builderForValue) {
        ensureWordIsMutable();
        word_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder addWord(
          int index, personal.eido.ezmemory.data.WordProtos.Word.Builder builderForValue) {
        ensureWordIsMutable();
        word_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder addAllWord(
          java.lang.Iterable<? extends personal.eido.ezmemory.data.WordProtos.Word> values) {
        ensureWordIsMutable();
        super.addAll(values, word_);

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder clearWord() {
        word_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .data.Word word = 1;</code>
       */
      public Builder removeWord(int index) {
        ensureWordIsMutable();
        word_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:data.WordList)
    }

    static {
      defaultInstance = new WordList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data.WordList)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
